version: "3.8"

services:
  app:
    build: .
    env_file:
      - .env
    container_name: bharat_itinerary_guru_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "start:dev"]

  test:
    build: .
    container_name: test_runner
    volumes:
      - .:/app
    command: ["npm", "run", "test"]
